Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,33 +18,33 @@ jobs:
             #   run: |
             #       echo "Deployment failed"
             #       exit 1
-    deploy-resume:
-        # needs: build
-        # if: success()
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout
-              uses: actions/checkout@v4
-            - name: Fetch main
-              run: |
-                  git config --global user.name "GitHub Actions"
-                  git config --global user.email "actions@github.com"
-                  git fetch
-            - name: Commit and Push Resume
-              run: |
-                  git add data/docs/
-                  git commit -m "Update Docs" || echo "No changes to commit"
-                  git pull
-                  git push || (echo "Failed to push changes" && exit 1)
-            - name: Fetch gh-pages
-              run: |
-                  git config --global user.name "GitHub Actions"
-                  git config --global user.email "actions@github.com"
-                  git fetch
-                  git checkout gh-pages || (echo "Failed to checkout gh-pages branch" && exit 1)
-            - name: Commit and Push Resume
-              run: |
-                  git checkout main -- data/docs/
-                  git add data/docs/
-                  git commit -m "Update Docs" || echo "No changes to commit"
-                  git push || (echo "Failed to push changes" && exit 1)
+    # deploy-resume:
+    #     # needs: build
+    #     # if: success()
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Checkout
+    #           uses: actions/checkout@v4
+    #         - name: Fetch main
+    #           run: |
+    #               git config --global user.name "GitHub Actions"
+    #               git config --global user.email "actions@github.com"
+    #               git fetch
+    #         - name: Commit and Push Resume
+    #           run: |
+    #               git add data/docs/
+    #               git commit -m "Update Docs" || echo "No changes to commit"
+    #               git pull
+    #               git push || (echo "Failed to push changes" && exit 1)
+    #         - name: Fetch gh-pages
+    #           run: |
+    #               git config --global user.name "GitHub Actions"
+    #               git config --global user.email "actions@github.com"
+    #               git fetch
+    #               git checkout gh-pages || (echo "Failed to checkout gh-pages branch" && exit 1)
+    #         - name: Commit and Push Resume
+    #           run: |
+    #               git checkout main -- data/docs/
+    #               git add data/docs/
+    #               git commit -m "Update Docs" || echo "No changes to commit"
+    #               git push || (echo "Failed to push changes" && exit 1)
